- name: "💥 Breaking Change"
  color: ee0701
  description: "This update will break existing functionality. Proceed with caution."

- name: "🐛 Bug"
  color: ee0701
  description: "Something isn't working right. Fix it before it becomes self-aware."

- name: "📖 Documentation"
  color: 0052cc
  description: "Changes related to documentation. Because words matter too."

- name: "🚀 Enhancement"
  color: 1d76db
  description: "Improving something that already exists but making it cooler."

- name: "🛠️ Refactor"
  color: 1d76db
  description: "Code improvements without changing functionality. Like a code spa day."

- name: "⚡ Performance"
  color: 1d76db
  description: "Making things run faster. Because speed matters."

- name: "✨ New Feature"
  color: 0e8a16
  description: "Adding something shiny and new to the project."

- name: "🔧 Maintenance"
  color: 2af79e
  description: "General project upkeep. Nothing exciting, but necessary."

- name: "📦 Dependencies"
  color: 1d76db
  description: "Updating, adding, or removing dependencies. Hope nothing breaks."

- name: "🛑 Won't Fix"
  color: ffffff
  description: "This issue won't be fixed. Probably because it's not an issue."

- name: "💤 Stale"
  color: fef2c0
  description: "This issue or PR has been gathering dust."

- name: "🚫 No Stale"
  color: fef2c0
  description: "This issue or PR is immune to the Stale Bot's wrath."

- name: "🔒 Security"
  color: ee0701
  description: "This is a security issue. Handle it before hackers do."

- name: "🤷 Incomplete"
  color: fef2c0
  description: "This issue or PR is missing important details. Fill in the blanks."

- name: "🚫 Invalid"
  color: fef2c0
  description: "This issue or PR doesn’t meet requirements. Try again."

- name: "👶 Beginner Friendly"
  color: 0e8a16
  description: "A good first issue for new contributors. We believe in you!"

- name: "🆘 Help Wanted"
  color: 0e8a16
  description: "Need extra hands on this. Or just a shoulder to cry on."

- name: "🧪 Experimental"
  color: bfdadc
  description: "An experimental feature or issue. Might work. Might not."

- name: "☢️ Priority: Critical"
  color: ee0701
  description: "This needs fixing ASAP. The world might end otherwise."

- name: "⚡ Priority: High"
  color: b60205
  description: "Should be done soon, but we won’t lose sleep over it… yet."

- name: "🔥 Priority: Medium"
  color: 0e8a16
  description: "Nice to have, but not urgent. Maybe next sprint. Maybe never."

- name: "❄️ Priority: Low"
  color: e4ea8a
  description: "If we ever get bored, we might fix this."

- name: "🙃 Duplicate"
  color: cfd3d7
  description: "This issue or PR already exists. Check before submitting."

- name: "🚀 Release"
  color: bada55
  description: "This is related to a new release. Pop the champagne!"

- name: "🔟 Major"
  color: b60205
  description: "This PR requires a major version bump. Big changes incoming!"

- name: "🔢 Minor"
  color: 0e8a16
  description: "This PR causes a minor version bump. Small but important."

- name: "⏳ Time: Long"
  color: 333333
  description: "This will take about a week. Buckle up."

- name: "⌚ Time: Medium"
  color: 999999
  description: "A few days of work. Manageable."

- name: "⏲️ Time: Short"
  color: eeeeee
  description: "A few hours of effort. Easy peasy."
