blank_issues_enabled: true
contact_links:
  - name: GitHub Discussions
    url: https://github.com/babyico/.../discussions
    about: Start a discussion
  - name: Discord support server
    url: https://discord.gg/EXHhWpb5ps
    about: The best place to go for help installing or using Babyicos's games and softwares.
