name: Sync labels
on:
  workflow_dispatch:

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout ARepo
        uses: actions/checkout@v4
        with:
          repository: babyico/CarDash
      
      - uses: EndBug/label-sync@v2
        with:
          config-file: 'https://raw.githubusercontent.com/babyico/.github/master/.github/labels.yml'
          token: ${{ secrets.TOKEN }}
